#!/bin/sh

# set environemt stuff
# PATH should contain at least /usr/local/sbin, /usr/sbin and /sbin
PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin
# some parts of apt-get seem to need term set to something
TERM=dumb

# This function returns the lowercase name of the linux distribution we're 
# running on. Currently I only care about Ubuntu and CentOS, so that's all 
# it detects.
detect_distribution ()
{
	if [ -f /etc/lsb-release ] ; then
		echo "ubuntu"
	elif [ -f /etc/redhat-release ] ; then
		echo "centos"
	fi
}

# This function does not output anything if there are no packages to update or
# if the distribution cannot be detected.
get_available_updates ()
{
	distro=`detect_distribution`
	if [ "x$distro" = xubuntu ] ; then
		#for ubuntu
		updates=`apt-get dist-upgrade -Vs 2>&1|grep ^Inst | cut -d " " -f 2`
		echo $updates
	elif [ "x$distro" = xcentos ] ; then
		#for centos
		updates=`yum check-update -q | grep -v " \* \|^$" | cut -d " " -f 1 | cut -d "." -f 1 | uniq`
		echo $updates
	fi
}

# Replaces spaces with commas
spaces_to_commas ()
{
	echo $1 | sed 's/ \+/,/g'
}

# Returns true if a reboot is needed, false otherwise
is_reboot_needed()
{
	distro=`detect_distribution`
	if [ "x$distro" = "xubuntu" ]; then
		if [ -f /var/run/reboot-required ]; then
			echo "true"
		else
			echo "false"
		fi
	elif [ "x$distro" = "xcentos" ]; then
		# I assume that a kernel is the only thing that would require a
		# reboot. There could be other things that need it as well.
		running_kernel=`uname -a |cut -d " " -f 3`
		newest_kernel=`yum -q list kernel | grep "installed" | awk -F" " '{ print $2 }' | sort -n -s | sed '$!d'`
		if [ "x$running_kernel" != "x$newest_kernel"  ]; then
			echo "true"
		else
			echo "false"
		fi
	else
		echo "unknown"
	fi
}

# Invokes package manager to do updates on selected packages.
# Takes a space separated list of packages.
do_updates()
{
	distro=`detect_distribution`
	if [ "x$distro" = "xubuntu" ]; then
		results=`apt-get -q -y -o DPkg::Options::\=--force-confold install $1 2>&1`
		if [ $? -ne 0 ]; then
			echo "apt-get install did not execute successfully"
			echo $results
		fi
	elif [ "x$distro" = "xcentos" ]; then
		results=`yum -y update $1`
		if [ $? -ne 0 ]; then
			echo "yum update did not execute successfully"
			echo $results
		fi
	fi
}

# include config file
. /etc/forest-client.conf

# build urls to use for posting and getting data
post_url="$server_url/collect.php"
accepted_url="$server_url/getaccepted.php?system=`hostname`"

# check for accepted updates and apply them
accepted_updates=`curl --silent --show-error $accepted_url`
# quit here silently if curl can't connect
if [ $? -ne 0 ]; then
	exit 0
fi
# only try to apply updates if the list isn't empty
if [ "x$accepted_updates" != "x" ]; then
	do_updates "$accepted_updates"
fi

# collect packages available for update and report them
postdata1="system_name=`hostname`"
formatted_updates=`get_available_updates`
if [ "x$formatted_updates" != "x" ]; then
	formatted_updates=`spaces_to_commas "$formatted_updates"`
	postdata2="available_updates=$formatted_updates"
else
	postdata2="no_updates_available=true"
fi

formatted_reboot="reboot_required=`is_reboot_needed`"

curldata=`curl --silent --show-error --data "$postdata1" --data "$postdata2" --data "$formatted_reboot" $post_url`

# filter out success messege and return value of grep to avoid cron warning messages
if [ "x$1" = "x--cron" ]; then
	curldata=`echo "$curldata" | grep -v "data ok"`
fi

# output anything from curl that hasn't been filtered
if [ "x" != "x$curldata" ]; then
	echo $curldata
fi
