#!/bin/sh

# This function returns the lowercase name of the linux distribution we're 
# running on. Currently I only care about Ubuntu and CentOS, so that's all 
# it detects.
detect_distribution ()
{
	if [ -f /etc/lsb-release ] ; then
		echo "ubuntu"
	elif [ -f /etc/redhat-release ] ; then
		echo "centos"
	fi
}

# This function does not output anything if there are no packages to update or
# if the distribution cannot be detected.
get_available_updates ()
{
	distro=`detect_distribution`
	if [ "x$distro" -eq "xubuntu" ] ; then
		#for ubuntu
		updates=`apt-get dist-upgrade -Vs |grep ^Inst | cut -d " " -f 2`
		echo $updates
	elif [ "x$distro" -eq "xcentos" ] ; then
		#for centos - NOT TESTED!!!
		updates=`yum check-update | grep -v "Loaded plugins:\|Loading mirror speeds\| \* \|^$" | cut -d " " -f 1`
		echo $updates
	fi
}

# Replaces spaces with commas
spaces_to_commas ()
{
	echo $1 | sed 's/ \+/,/g'
}

# Returns truw if a reboot is needed, false otherwise
is_reboot_needed()
{
	distro=`detect_distribution`
	if [ "x$distro" -eq "xubuntu" ]; then
		if [ -f /var/run/reboot-required ]; then
			echo "true"
		else
			echo "false"
		fi
	else
		echo "unknown"
	fi
}

# include config file
. /etc/forest-client.conf

postdata1="system_name=`hostname`"
formatted_updates=`get_available_updates`
if [ "x$formatted_updates" != "x" ]; then
	formatted_updates=`spaces_to_commas "$formatted_updates"`
	postdata2="available_updates=$formatted_updates"
else
	postdata2="no_updates_available=true"
fi

formatted_reboot="reboot_needed=`is_reboot_needed`"

curldata=`curl --silent --show-error --data-urlencode "$postdata1" --data-urlencode "$postdata2" --data-urlencode "$formatted_reboot" $posturl`

#filter out success message and return value of grep for cron
if [ "x$1" = "x--cron" ]; then
	curldata=`echo "$curldata" | grep -v "data ok"`
fi

echo $curldata
