#!/bin/sh

# This function does not output anything if there are no packages to update or
# if the distribution cannot be detected.
get_available_updates ()
{
	if [ -f /etc/lsb-release ] ; then
		#for ubuntu
		updates=`apt-get dist-upgrade -Vs |grep ^Inst | cut -d " " -f 2`
		echo $updates
	elif [ -f /etc/redhat-release ] ; then
		#for centos - NOT TESTED!!!
		updates=`yum check-update | grep -v "Loaded plugins:\|Loading mirror speeds\| \* \|^$" | cut -d " " -f 1`
		echo $updates
	fi
}

# Replaces spaces with commas
spaces_to_commas ()
{
	echo $1 | sed 's/ \+/,/g'
}

# include config file
. /etc/forest-client.conf

postdata1="system_name=`hostname`"
formatted_updates=`get_available_updates`
if [ "x$formatted_updates" != "x" ]; then
	formatted_updates=`spaces_to_commas "$formatted_updates"`
	postdata2="available_updates=$formatted_updates"
else
	postdata2="no_updates_available=true"
fi

curldata=`curl --silent --show-error --data-urlencode "$postdata1" --data-urlencode "$postdata2" $posturl`

#filter out success message and return value of grep for cron
if [ "x$1" = "x--cron" ]; then
	curldata=`echo "$curldata" | grep -v "data ok"`
fi

echo $curldata
