#!/bin/sh

# only run if the package is completely installed
test -x /usr/sbin/forest-collect || exit 0

returndata=`/usr/sbin/forest-collect`
if [ $? -ne 0 ]
then
	echo "forest-collect return value: $?\n"
	echo $returndata
fi

returndata=`echo $returndata | grep -v "data ok"`
# Grep returns 0 if it finds the search string, or 1 if it doesn't.
# A return value of anything but 0 means we want to see the message.
if [ $? -ne 0 ]
then
	echo "grep return value: $?\n"
	echo $returndata
fi
