#!/bin/sh
if [ -f /etc/lsb-release ] ; then
	#for ubuntu
	updates=`apt-get dist-upgrade -Vs |grep ^Inst | cut -d " " -f 2`
	echo $updates
elif [ -f /etc/redhat-release ] ; then
	#for centos
	updates=`yum check-update | grep -v "Loaded plugins:\|Loading mirror speeds\| \* \|^$" | cut -d " " -f 1`
	echo $updates
else
	echo "Can't determine distribution"
fi
