REM Run this script after changing version.txt to propigate the version
REM to all the proper places.

set /p Version=<version.txt
FOR /F "delims=" %%i IN ('"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\uuidgen.exe"') DO set Uuid=%%i

set Message1=This file is automatically generated by update-version script.
set Message2=Any changes will be overwritten next time the script is run.

set c_filename=client\version.h
set rc1_filename=client\Windows\version1.rc
set rc2_filename=client\Windows\version2.rc
set php_filename=server\www\application\config\version.php
set cs_filename=client\Windows\COnfigurationGUI\Properties\version.cs
set wix_filename=client\Windows\ForestInstaller\FOrestInstaller\Version.wxi

REM C version
echo // %Message1% > %c_filename%
echo // %Message2% >> %c_filename%
echo #define FOREST_VERSION "%Version%" >> %c_filename%

REM C Resource version 1
set special_version=%Version:.=,%
echo // %Message1% > %rc1_filename%
echo // %Message2% >> %rc1_filename%
echo FILEVERSION %special_version%,0 >> %rc1_filename%
echo PRODUCTVERSION %special_version%,0 >> %rc1_filename%

REM C Resource version 2
echo // %Message1% > %rc2_filename%
echo // %Message2% >> %rc2_filename%
echo VALUE "FileVersion", "%Version%.0" >> %rc2_filename%
echo VALUE "ProductVersion", "%Version%.0" >> %rc2_filename%

REM PHP version
echo ^<?php > %php_filename%
echo // %Message1% >> %php_filename%
echo // %Message2% >> %php_filename%
echo $config['forest_version'] = "%Version%"; >> %php_filename%

REM C# version
echo // %Message1% > %cs_filename%
echo // %Message2% >> %cs_filename%
echo using System.Reflection; >> %cs_filename%
echo [assembly: AssemblyVersion("%Version%.0")] >> %cs_filename%
echo [assembly: AssemblyFileVersion("%Version%.0")] >> %cs_filename%

REM Wix version
echo ^<?xml version="1.0" encoding="utf-8"?^> > %wix_filename%
echo ^<!-- %Message1% --^> >> %wix_filename%
echo ^<!-- %Message2% --^> >> %wix_filename%
echo ^<Include^> >> %wix_filename%
echo   ^<?define ProductVersion = "%Version%"?^> >> %wix_filename%
echo   ^<?define ProductUuid = "%Uuid%"?^> >> %wix_filename%
echo ^</Include^> >> %wix_filename%

pause
