// This file is automatically generated by update-version script.
// Any changes will be overwritten next time the script is run.
using System.Reflection; 
[assembly: AssemblyVersion("1.2.4.0")] 
[assembly: AssemblyFileVersion("1.2.4.0")] 
