// This file is automatically generated by update-version.sh.
// Any updates will be overwritten.
using System.Reflection;
[assembly: AssemblyVersion("1.1.3.0")]
[assembly: AssemblyFileVersion("1.1.3.0")]
